# Generated by Django 5.2.5 on 2025-11-18 09:14

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('preferencias', models.TextField(blank=True, help_text='Vegetariano, Celiaco, etc.')),
                ('notas', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de Mesa')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad Personas')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'En Limpieza')], default='LIBRE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('LLEGO', 'Cliente Llegó'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='MainApp.cliente')),
                ('mesa_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.mesa')),
            ],
        ),
    ]
