# Generated by Django 5.2.5 on 2025-11-18 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha Reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fin'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
    ]
